
- name: Setup Web Server
  hosts: managed_hosts
  become: yes

  tasks:

    - name: Ensure Apache is installed
      apt:
        update_cache: yes
        name: apache2
        state: present

    - name: Ensure Apache is Running
      service: 
        name: apache2
        state: started


